spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
  flyway:
    enabled: true
    clean-on-validation-error: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE